name: release

on:
  release: null
  push:
    tags: 'urbit-v[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  call-vere:
    permissions:
      contents: none
    uses: ./.github/workflows/vere.yml
    with:
      pace: 'live'
      upload: true
    secrets: inherit
